### ISSUE TITLE
Error when `step` is set to `any`

### ISSUE THREAD

**Issue by romaincazier** [eelke/InputfieldFloatRange#3]
Hi!

I just installed your module and I noticed an error is triggered when [`step` is set to `"any"`](https://github.com/eelke/InputfieldFloatRange/blob/3cc418563df3d856c2bab6dafea56b43e69998a0/InputfieldFloatRange.module#L67-L69).

When the `roundValue()` function is called this [if statement](https://github.com/eelke/InputfieldFloatRange/blob/3cc418563df3d856c2bab6dafea56b43e69998a0/InputfieldFloatRange.module#L116) returns `true` and leads the code to error when trying to use `"any"` as a number.

A simple fix would be to add `$step !== "any"`.

**Comment by eelke** [comment]
Thanks for reporting this issue @romaincazier! I'll push an update for this soon.
